/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as EmbedViewerRouteImport } from './routes/embed.viewer'
import { Route as ApiPublicWidgetRouteImport } from './routes/api/public/widget'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicStoreStoreIdRouteImport } from './routes/api/public/store.$storeId'
import { Route as ApiPublicStoreStoreIdStoriesRouteImport } from './routes/api/public/store.$storeId.stories'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedViewerRoute = EmbedViewerRouteImport.update({
  id: '/embed/viewer',
  path: '/embed/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetRoute = ApiPublicWidgetRouteImport.update({
  id: '/api/public/widget',
  path: '/api/public/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoreStoreIdRoute = ApiPublicStoreStoreIdRouteImport.update({
  id: '/api/public/store/$storeId',
  path: '/api/public/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoreStoreIdStoriesRoute =
  ApiPublicStoreStoreIdStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => ApiPublicStoreStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/embed/viewer': typeof EmbedViewerRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/store/$storeId': typeof ApiPublicStoreStoreIdRouteWithChildren
  '/api/public/store/$storeId/stories': typeof ApiPublicStoreStoreIdStoriesRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/embed/viewer': typeof EmbedViewerRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/store/$storeId': typeof ApiPublicStoreStoreIdRouteWithChildren
  '/api/public/store/$storeId/stories': typeof ApiPublicStoreStoreIdStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/embed/viewer': typeof EmbedViewerRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/store/$storeId': typeof ApiPublicStoreStoreIdRouteWithChildren
  '/api/public/store/$storeId/stories': typeof ApiPublicStoreStoreIdStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/embed/viewer'
    | '/api/public/track'
    | '/api/public/widget'
    | '/api/public/store/$storeId'
    | '/api/public/store/$storeId/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/embed/viewer'
    | '/api/public/track'
    | '/api/public/widget'
    | '/api/public/store/$storeId'
    | '/api/public/store/$storeId/stories'
  id:
    | '__root__'
    | '/$'
    | '/embed/viewer'
    | '/api/public/track'
    | '/api/public/widget'
    | '/api/public/store/$storeId'
    | '/api/public/store/$storeId/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  EmbedViewerRoute: typeof EmbedViewerRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicWidgetRoute: typeof ApiPublicWidgetRoute
  ApiPublicStoreStoreIdRoute: typeof ApiPublicStoreStoreIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/viewer': {
      id: '/embed/viewer'
      path: '/embed/viewer'
      fullPath: '/embed/viewer'
      preLoaderRoute: typeof EmbedViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget': {
      id: '/api/public/widget'
      path: '/api/public/widget'
      fullPath: '/api/public/widget'
      preLoaderRoute: typeof ApiPublicWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store/$storeId': {
      id: '/api/public/store/$storeId'
      path: '/api/public/store/$storeId'
      fullPath: '/api/public/store/$storeId'
      preLoaderRoute: typeof ApiPublicStoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store/$storeId/stories': {
      id: '/api/public/store/$storeId/stories'
      path: '/stories'
      fullPath: '/api/public/store/$storeId/stories'
      preLoaderRoute: typeof ApiPublicStoreStoreIdStoriesRouteImport
      parentRoute: typeof ApiPublicStoreStoreIdRoute
    }
  }
}

interface ApiPublicStoreStoreIdRouteChildren {
  ApiPublicStoreStoreIdStoriesRoute: typeof ApiPublicStoreStoreIdStoriesRoute
}

const ApiPublicStoreStoreIdRouteChildren: ApiPublicStoreStoreIdRouteChildren = {
  ApiPublicStoreStoreIdStoriesRoute: ApiPublicStoreStoreIdStoriesRoute,
}

const ApiPublicStoreStoreIdRouteWithChildren =
  ApiPublicStoreStoreIdRoute._addFileChildren(
    ApiPublicStoreStoreIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  EmbedViewerRoute: EmbedViewerRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicWidgetRoute: ApiPublicWidgetRoute,
  ApiPublicStoreStoreIdRoute: ApiPublicStoreStoreIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
