/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as EmbedViewerRouteImport } from './routes/embed.viewer'
import { Route as ApiPublicZtEvRouteImport } from './routes/api/public/zt-ev'
import { Route as ApiPublicZtCfgRouteImport } from './routes/api/public/zt-cfg'
import { Route as ApiPublicStoreStoreIdRouteImport } from './routes/api/public/store.$storeId'
import { Route as ApiPublicStoreStoreIdStoriesRouteImport } from './routes/api/public/store.$storeId.stories'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedViewerRoute = EmbedViewerRouteImport.update({
  id: '/embed/viewer',
  path: '/embed/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZtEvRoute = ApiPublicZtEvRouteImport.update({
  id: '/api/public/zt-ev',
  path: '/api/public/zt-ev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZtCfgRoute = ApiPublicZtCfgRouteImport.update({
  id: '/api/public/zt-cfg',
  path: '/api/public/zt-cfg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoreStoreIdRoute = ApiPublicStoreStoreIdRouteImport.update({
  id: '/api/public/store/$storeId',
  path: '/api/public/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoreStoreIdStoriesRoute =
  ApiPublicStoreStoreIdStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => ApiPublicStoreStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/embed/viewer': typeof EmbedViewerRoute
  '/api/public/zt-cfg': typeof ApiPublicZtCfgRoute
  '/api/public/zt-ev': typeof ApiPublicZtEvRoute
  '/api/public/store/$storeId': typeof ApiPublicStoreStoreIdRouteWithChildren
  '/api/public/store/$storeId/stories': typeof ApiPublicStoreStoreIdStoriesRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/embed/viewer': typeof EmbedViewerRoute
  '/api/public/zt-cfg': typeof ApiPublicZtCfgRoute
  '/api/public/zt-ev': typeof ApiPublicZtEvRoute
  '/api/public/store/$storeId': typeof ApiPublicStoreStoreIdRouteWithChildren
  '/api/public/store/$storeId/stories': typeof ApiPublicStoreStoreIdStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/embed/viewer': typeof EmbedViewerRoute
  '/api/public/zt-cfg': typeof ApiPublicZtCfgRoute
  '/api/public/zt-ev': typeof ApiPublicZtEvRoute
  '/api/public/store/$storeId': typeof ApiPublicStoreStoreIdRouteWithChildren
  '/api/public/store/$storeId/stories': typeof ApiPublicStoreStoreIdStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/embed/viewer'
    | '/api/public/zt-cfg'
    | '/api/public/zt-ev'
    | '/api/public/store/$storeId'
    | '/api/public/store/$storeId/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/embed/viewer'
    | '/api/public/zt-cfg'
    | '/api/public/zt-ev'
    | '/api/public/store/$storeId'
    | '/api/public/store/$storeId/stories'
  id:
    | '__root__'
    | '/$'
    | '/embed/viewer'
    | '/api/public/zt-cfg'
    | '/api/public/zt-ev'
    | '/api/public/store/$storeId'
    | '/api/public/store/$storeId/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  EmbedViewerRoute: typeof EmbedViewerRoute
  ApiPublicZtCfgRoute: typeof ApiPublicZtCfgRoute
  ApiPublicZtEvRoute: typeof ApiPublicZtEvRoute
  ApiPublicStoreStoreIdRoute: typeof ApiPublicStoreStoreIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/viewer': {
      id: '/embed/viewer'
      path: '/embed/viewer'
      fullPath: '/embed/viewer'
      preLoaderRoute: typeof EmbedViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zt-ev': {
      id: '/api/public/zt-ev'
      path: '/api/public/zt-ev'
      fullPath: '/api/public/zt-ev'
      preLoaderRoute: typeof ApiPublicZtEvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zt-cfg': {
      id: '/api/public/zt-cfg'
      path: '/api/public/zt-cfg'
      fullPath: '/api/public/zt-cfg'
      preLoaderRoute: typeof ApiPublicZtCfgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store/$storeId': {
      id: '/api/public/store/$storeId'
      path: '/api/public/store/$storeId'
      fullPath: '/api/public/store/$storeId'
      preLoaderRoute: typeof ApiPublicStoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store/$storeId/stories': {
      id: '/api/public/store/$storeId/stories'
      path: '/stories'
      fullPath: '/api/public/store/$storeId/stories'
      preLoaderRoute: typeof ApiPublicStoreStoreIdStoriesRouteImport
      parentRoute: typeof ApiPublicStoreStoreIdRoute
    }
  }
}

interface ApiPublicStoreStoreIdRouteChildren {
  ApiPublicStoreStoreIdStoriesRoute: typeof ApiPublicStoreStoreIdStoriesRoute
}

const ApiPublicStoreStoreIdRouteChildren: ApiPublicStoreStoreIdRouteChildren = {
  ApiPublicStoreStoreIdStoriesRoute: ApiPublicStoreStoreIdStoriesRoute,
}

const ApiPublicStoreStoreIdRouteWithChildren =
  ApiPublicStoreStoreIdRoute._addFileChildren(
    ApiPublicStoreStoreIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  EmbedViewerRoute: EmbedViewerRoute,
  ApiPublicZtCfgRoute: ApiPublicZtCfgRoute,
  ApiPublicZtEvRoute: ApiPublicZtEvRoute,
  ApiPublicStoreStoreIdRoute: ApiPublicStoreStoreIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
